---
# Upgrade ceph cluster properly
# * Preparations
# * Upgrade monitors one by one
# * Upgrade OSDs one by one

# Preparations:
# - install helper tools
# - configure repositories
# - synchronize time
# - download the packages

- hosts:
    - mons
    - osds
    - clients

  become: True
  pre_tasks:
    - name: install pre-dependencies
      package: >
        name={{ item }}
        state=present
      with_items:
        - "python-pycurl"
        - hdparm
        - ntp
        - "python-apt"

    - include: ./tasks/timesync.yml
      when: "{{ do_time_sync|default(False)|bool }}"

    - include: ./tasks/aptrepos.yml
      when: "{{ not(use_mos_ceph|default(True)|bool) }}"

    - name: grab the packages into local cache
      command: >
        apt-get install -y --download-only 
        {{ debian_ceph_packages|join(' ') }}
        {{ debian_radosgw_packages|join(' ') }}

  environment: "{{ proxy_env }}"

- hosts: mons
  become: True
  serial: 1
  tasks:
    - include: ./tasks/install_upgrade_packages.yml
    - include: ./tasks/restart_mons.yml
  vars:
    mon_restart_delay: 5
    mon_restart_attempts: 20

# Upgrade OSDs. On each OSD node
# - Upgrade/install ceph packages
# - Set flags to prevent data rebalancing
# - Restart OSDs on the node
# - Wait for recovery to complete
# - Proceed to the next node

- hosts: osds
  become: True
  serial: 1
  tasks:
    - include: ./tasks/install_upgrade_packages.yml
    - include: ./tasks/restart_osds.yml
  environment: "{{ proxy_env }}"


# Upgrade ceph clients (hypervisor nodes).
# - Install/upgrade ceph packages
# - TODO: Restart processes using ceph client libraries

- hosts: clients
  become: True
  tasks:
    - include: ./tasks/install_upgrade_packages.yml
  environment: "{{ proxy_env }}"

